version: '3'

services:
  nginx:
    image: nginx:snouae
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - '443:443'
    restart: always
    env_file:
      - .env

  mariadb:
    image: mariadb:snouae
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    image: wordpress:snouae
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env

volumes:
  wordpress:
        driver: local
        driver_opts:
            device: /home/snouae/Desktop/data/wordpress
            o: bind
            type: none
  mariadb:
        driver: local
        driver_opts:
            device: /home/snouae/Desktop/data/mariadb
            o: bind
            type: none

networks:
  inception:
    name: inception

